name: updata_arkchar_data

on: 
  # push:
  #   branches: 
  #    - master
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: start
      run: |
        cd script
        pip install -r updata_arkchar_data_requirements.txt
        python updata_arkchar_data.py

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: /
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}